apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-flutter
  namespace: kpmg-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-flutter
  template:
    metadata:
      labels:
        app: web-flutter
    spec:
      containers:
        - name: web-flutter
          image: web-flutter:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-flutter
  namespace: kpmg-poc
spec:
  selector:
    app: web-flutter
  ports:
    - port: 80
      targetPort: 80
